[package]
name = "airflow-common"
version = "0.1.0"
edition = "2024"
description = "Common definitions and traits for working with Airflow."
license-file = "../LICENSE"

[dependencies]

[features]
default = ["std"]
std = []
