[package]
name = "airflow-common"
version = "0.1.0"
edition = "2024"
description = "Common definitions and traits for working with Airflow."
license-file = "../LICENSE"

[dependencies]
cfg-if = "1"
chrono = { version = "0.4", default-features = false, features = ["serde", "alloc"] }
jsonwebtoken = { version = "9", default-features = false, optional = true }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
uuid = { version = "1", default-features = false, features = ["serde"] }

[features]
default = ["jsonwebtoken", "now", "std"]
jsonwebtoken = ["dep:jsonwebtoken"]
now = ["chrono/now"]
std = ["chrono/std", "serde/std", "uuid/std"]
