[package]
name = "airflow-common"
version = "0.1.0"
edition = "2024"
description = "Common definitions and traits for working with Airflow."
license-file = "../LICENSE"

[dependencies]
cfg-if = "1"
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }

[features]
default = ["std"]
std = ["serde/std"]
