name: CI

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - name: Build
            command: build
            args: --release
          - name: Format
            command: fmt
            args: --all -- --check
          - name: Clippy
            command: clippy
            args: --all-features --workspace -- -D warnings
          - name: Test (default features)
            command: test
            # TODO test no-std features only
          - name: Test (all features)
            command: test
            args: --all-features
          - name: Test (no default features)
            command: test
            args: --no-default-features

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rust-src, rustfmt, clippy
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
